// Code generated by Slice Machine. DO NOT EDIT.

import Gitbutton from './Gitbutton/index.svelte';
import Paragraphtext from './Paragraphtext/index.svelte';
import Profileimg from './Profileimg/index.svelte';
import Titleblock from './Titleblock/index.svelte';

export const components = {
	gitbutton: Gitbutton,
	paragraphtext: Paragraphtext,
	profileimg: Profileimg,
	titleblock: Titleblock
};
