// Code generated by Slice Machine. DO NOT EDIT.

import Profiel from './Profiel/index.svelte';
import Titleblock from './Titleblock/index.svelte';

export const components = {
	profiel: Profiel,
	titleblock: Titleblock
};
