// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *nav → nav*
 */
export interface NavDocumentDataNavItem {}

/**
 * Content for nav documents
 */
interface NavDocumentData {
	/**
	 * nav field in *nav*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.nav[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	nav: prismic.GroupField<Simplify<NavDocumentDataNavItem>>;
}

/**
 * nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<NavDocumentData>,
	'nav',
	Lang
>;

type VisitekaartjeDocumentDataSlicesSlice = TitleblockSlice;

/**
 * Content for Visitekaartje documents
 */
interface VisitekaartjeDocumentData {
	/**
	 * Slice Zone field in *Visitekaartje*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: visitekaartje.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<VisitekaartjeDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *Visitekaartje*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: visitekaartje.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Visitekaartje*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: visitekaartje.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *Visitekaartje*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: visitekaartje.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * Visitekaartje document from Prismic
 *
 * - **API ID**: `visitekaartje`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VisitekaartjeDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<VisitekaartjeDocumentData>,
	'visitekaartje',
	Lang
>;

export type AllDocumentTypes = NavDocument | VisitekaartjeDocument;

/**
 * Primary content in *Profiel → Primary*
 */
export interface ProfielSliceDefaultPrimary {
	/**
	 * Title field in *Profiel → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: profiel.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Img field in *Profiel → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: profiel.primary.img
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	img: prismic.ImageField<never>;
}

/**
 * Default variation for Profiel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProfielSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ProfielSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Profiel*
 */
type ProfielSliceVariation = ProfielSliceDefault;

/**
 * Profiel Shared Slice
 *
 * - **API ID**: `profiel`
 * - **Description**: Profiel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProfielSlice = prismic.SharedSlice<'profiel', ProfielSliceVariation>;

/**
 * Default variation for Titleblock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleblockSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	never
>;

/**
 * Slice variation for *Titleblock*
 */
type TitleblockSliceVariation = TitleblockSliceDefault;

/**
 * Titleblock Shared Slice
 *
 * - **API ID**: `titleblock`
 * - **Description**: Titleblock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleblockSlice = prismic.SharedSlice<'titleblock', TitleblockSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			NavDocument,
			NavDocumentData,
			NavDocumentDataNavItem,
			VisitekaartjeDocument,
			VisitekaartjeDocumentData,
			VisitekaartjeDocumentDataSlicesSlice,
			AllDocumentTypes,
			ProfielSlice,
			ProfielSliceDefaultPrimary,
			ProfielSliceVariation,
			ProfielSliceDefault,
			TitleblockSlice,
			TitleblockSliceVariation,
			TitleblockSliceDefault
		};
	}
}
