// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ContactDocumentDataSlicesSlice = never;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
	/**
	 * Slice Zone field in *Contact*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ContactDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *Contact*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: contact.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Contact*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *Contact*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: contact.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<ContactDocumentData>,
	'contact',
	Lang
>;

/**
 * Item in *nav → nav*
 */
export interface NavDocumentDataNavItem {}

/**
 * Content for nav documents
 */
interface NavDocumentData {
	/**
	 * nav field in *nav*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.nav[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	nav: prismic.GroupField<Simplify<NavDocumentDataNavItem>>;
}

/**
 * nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<NavDocumentData>,
	'nav',
	Lang
>;

type VisitekaartjeDocumentDataSlicesSlice =
	| TitleblockSlice
	| ParagraphtextSlice
	| GitbuttonSlice
	| ProfileimgSlice;

/**
 * Content for Visitekaartje documents
 */
interface VisitekaartjeDocumentData {
	/**
	 * Slice Zone field in *Visitekaartje*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: visitekaartje.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<VisitekaartjeDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *Visitekaartje*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: visitekaartje.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Visitekaartje*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: visitekaartje.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *Visitekaartje*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: visitekaartje.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * Visitekaartje document from Prismic
 *
 * - **API ID**: `visitekaartje`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VisitekaartjeDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<VisitekaartjeDocumentData>,
	'visitekaartje',
	Lang
>;

export type AllDocumentTypes = ContactDocument | NavDocument | VisitekaartjeDocument;

/**
 * Primary content in *Gitbutton → Primary*
 */
export interface GitbuttonSliceDefaultPrimary {
	/**
	 * linkbutton field in *Gitbutton → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gitbutton.primary.linkbutton
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	linkbutton: prismic.LinkField;
}

/**
 * Default variation for Gitbutton Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GitbuttonSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<GitbuttonSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Gitbutton*
 */
type GitbuttonSliceVariation = GitbuttonSliceDefault;

/**
 * Gitbutton Shared Slice
 *
 * - **API ID**: `gitbutton`
 * - **Description**: Gitbutton
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GitbuttonSlice = prismic.SharedSlice<'gitbutton', GitbuttonSliceVariation>;

/**
 * Primary content in *Paragraphtext → Primary*
 */
export interface ParagraphtextSliceDefaultPrimary {
	/**
	 * keytext field in *Paragraphtext → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: paragraphtext.primary.keytext
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	keytext: prismic.KeyTextField;
}

/**
 * Default variation for Paragraphtext Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagraphtextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ParagraphtextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Paragraphtext*
 */
type ParagraphtextSliceVariation = ParagraphtextSliceDefault;

/**
 * Paragraphtext Shared Slice
 *
 * - **API ID**: `paragraphtext`
 * - **Description**: Paragraphtext
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagraphtextSlice = prismic.SharedSlice<'paragraphtext', ParagraphtextSliceVariation>;

/**
 * Primary content in *Profileimg → Primary*
 */
export interface ProfileimgSliceDefaultPrimary {
	/**
	 * profileimg field in *Profileimg → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: profileimg.primary.profileimg
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	profileimg: prismic.ImageField<never>;
}

/**
 * Default variation for Profileimg Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProfileimgSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ProfileimgSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Profileimg*
 */
type ProfileimgSliceVariation = ProfileimgSliceDefault;

/**
 * Profileimg Shared Slice
 *
 * - **API ID**: `profileimg`
 * - **Description**: Profileimg
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProfileimgSlice = prismic.SharedSlice<'profileimg', ProfileimgSliceVariation>;

/**
 * Primary content in *Titleblock → Primary*
 */
export interface TitleblockSliceDefaultPrimary {
	/**
	 * title field in *Titleblock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: titleblock.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
}

/**
 * Default variation for Titleblock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleblockSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TitleblockSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Titleblock*
 */
type TitleblockSliceVariation = TitleblockSliceDefault;

/**
 * Titleblock Shared Slice
 *
 * - **API ID**: `titleblock`
 * - **Description**: Titleblock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleblockSlice = prismic.SharedSlice<'titleblock', TitleblockSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			ContactDocument,
			ContactDocumentData,
			ContactDocumentDataSlicesSlice,
			NavDocument,
			NavDocumentData,
			NavDocumentDataNavItem,
			VisitekaartjeDocument,
			VisitekaartjeDocumentData,
			VisitekaartjeDocumentDataSlicesSlice,
			AllDocumentTypes,
			GitbuttonSlice,
			GitbuttonSliceDefaultPrimary,
			GitbuttonSliceVariation,
			GitbuttonSliceDefault,
			ParagraphtextSlice,
			ParagraphtextSliceDefaultPrimary,
			ParagraphtextSliceVariation,
			ParagraphtextSliceDefault,
			ProfileimgSlice,
			ProfileimgSliceDefaultPrimary,
			ProfileimgSliceVariation,
			ProfileimgSliceDefault,
			TitleblockSlice,
			TitleblockSliceDefaultPrimary,
			TitleblockSliceVariation,
			TitleblockSliceDefault
		};
	}
}
